### ISSUE TITLE
It's not work in Babel 6

### ISSUE THREAD

**Issue by welefen** [RReverser/babel-plugin-uglify#8]
> babel --presets es2015-loose,stage-1 --plugins transform-runtime,uglify src/ --out-dir lib/ --source-maps

TypeError: src/dependence.js: Cannot read property 'map' of undefined
    at Object.From_Moz_Program [as Program](eval at map %28eval at <anonymous> %28/Users/welefen/Develop/git/stcjs/stc-file/node_modules/babel-plugin-uglify/node_modules/.npminstall/uglify-js/2.6.2/uglify-js/tools/node.js:22:1%29%29, <anonymous>:7:13)
    at from_moz (eval at <anonymous> (/Users/welefen/Develop/git/stcjs/stc-file/node_modules/babel-plugin-uglify/node_modules/.npminstall/uglify-js/2.6.2/uglify-js/tools/node.js:22:1), <anonymous>:8416:54)
    at Function.AST_Node.from_mozilla_ast (eval at <anonymous> (/Users/welefen/Develop/git/stcjs/stc-file/node_modules/babel-plugin-uglify/node_modules/.npminstall/uglify-js/2.6.2/uglify-js/tools/node.js:22:1), <anonymous>:8424:19)
    at PluginPass.Program (/Users/welefen/Develop/git/stcjs/stc-file/node_modules/babel-plugin-uglify/dist/index.js:34:35)
    at newFn (/Users/welefen/Develop/git/stcjs/stc-file/node_modules/babel-traverse/lib/visitors.js:310:19)
    at NodePath._call (/Users/wele

**Comment by welefen** [comment]
It's throw error when exec code `var uAST = AST_Node.from_mozilla_ast(ast);`

**Comment by RReverser** [comment]
Please take a look at list of issues in any repo before submitting a new one. Thanks 😄
